-- return {
--   {
--     "mason-org/mason.nvim",
--     opts = {
--       ensure_installed = {
--         "vetur-vls",
--       },
--     },
--   },
-- }

-- {
--   "neovim/nvim-lspconfig",
--   opts = {
--     servers = {
--       -- 这里配置 volar
--       volar = {
--         init_options = {
--           vue = {
--             -- 对于 Vue 2，建议关闭混合模式以提高兼容性
--             hybridMode = false,
--           },
--         },
--         -- 如果你需要指定特定的文件类型
--         filetypes = { "typescript", "javascript", "javascriptreact", "typescriptreact", "vue", "json" },
--       },
--     },
--   },
-- },

-- return {
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         -- 1. 显式禁用 volar 和 vue_ls (防冲突)
--         volar = { enabled = false },
--         vue_ls = { enabled = false },
--         -- 2. 手动配置 vls (Vetur)
--         vuels = {
--           -- 关键：确保 vls 关联到 .vue 文件
--           filetypes = { "vue" },
--           settings = {
--             vetur = {
--               -- 针对纯 JS 项目的优化
--               useWorkspaceDependencies = true,
--               validation = {
--                 template = true,
--                 script = true,
--                 style = true,
--               },
--               completion = {
--                 autoImport = true,
--                 useScaffoldSnippets = true,
--                 tagCasing = "kebab", -- Vue 2 习惯
--               },
--               format = {
--                 enable = true, -- 如果你想让 Vetur 负责格式化
--                 defaultFormatter = {
--                   js = "prettier",
--                   html = "prettyhtml",
--                 },
--               },
--             },
--           },
--         },
--       },
--     },
--   },
-- }
